import Navbar from "@/components/Navbar"
import ReduxProvider from "@/redux/ReduxProvider"
import { ChakraProvider } from "@chakra-ui/react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Bhyve Interview Task",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <body
        className={inter.className}
        style={{ backgroundColor: "#e9e9e9", padding: "1rem" }}
        suppressHydrationWarning={true}
      >
        <ChakraProvider>
          <ReduxProvider>
            <Navbar />
          </ReduxProvider>
          {children}
        </ChakraProvider>
      </body>
    </html>
  )
}
